---
- name: Deploy Task Management API
  hosts: all
  become: yes
  vars:
    app_name: task-management-api
    app_port: 8080
    docker_image: "{{ docker_image | default('task-manager-api:latest') }}"
    db_username: "{{ db_username | default('taskmanager') }}"
    db_password: "{{ db_password | default('taskmanager123') }}"

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create application directory
      file:
        path: /opt/{{ app_name }}
        state: directory
        mode: '0755'

    - name: Copy docker-compose file
      template:
        src: docker-compose.yml.j2
        dest: /opt/{{ app_name }}/docker-compose.yml
        mode: '0644'

    - name: Deploy application with Docker Compose
      docker_compose:
        project_src: /opt/{{ app_name }}
        state: present
        pull: yes

    - name: Wait for application to be ready
      uri:
        url: http://localhost:{{ app_port }}/api/tasks/health
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 10

    - name: Display deployment status
      debug:
        msg: "Task Management API deployed successfully on port {{ app_port }}"
